FROM node:16-alpine as build

WORKDIR /app

COPY frontend/package*.json ./

RUN npm install

COPY frontend/src ./src
COPY frontend/public ./public

RUN npm run build

FROM node:16-alpine

WORKDIR /app

RUN npm install -g serve

COPY --from=build /app/build ./build

EXPOSE 3000

CMD ["serve", "-s", "build", "-l", "3000"]
